language: java
sudo: true
addons:
  apt:
    packages:
    - oracle-java8-installer
    - nodejs
install:
- wget -c https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-2.13.tgz
- tar -xf apache-jmeter-2.13.tgz
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4-sources.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4-javadoc.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/maciejzaleski/JMeter-WebSocketSampler/releases/download/version-1.0.2/JMeterWebSocketSampler-1.0.2-SNAPSHOT.jar
- wget -P https://github.com/MCS-Lite/mcs-lite-app/releases/download/v1.0.6/7688.tar.gz
- tar -zxf 7688.tar.gz && cd 7688
- node server.js&
- cd .. && pwd
before_script:
- ls -al
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/ant-jmeter-1.1.1.jar ./
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/collapse.png ./
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/expand.png ./
- ls -al
branches:
  only:
  - master
  - feature/auto-build
script:
- jdk_switcher use oraclejdk8
- ant -buildfile build.xml -Dtestpath=./ -Dtest=SmokeTest_lite -Djmeter.home="$TRAVIS_BUILD_DIR/apache-jmeter-2.13"
  -Dmcslite.host="localhost" -Dmcslite.port="80"
deploy:
  provider: s3
  access_key_id: AKIAJ36FA5PQGVMPSIVA
  secret_access_key:
    secure: DPk63LQ4QKxuj2Ykoopwx8KUIaLFZGfwz1BcRpZbviVKjZvBxoXtMUKH/P42Oaad/typ2K5FOx20o5qF3/uNBkMkBSZkc49fJhhMogSNKkuwm6EJwCh/1Gd49lL5qqRoYGwvGkakIPWq5syQHsHiAwr3GpbVzl8u4PAJ50v1F6gfBOGzYuQmW6dXP7ZAnQZdIxIBimOrvYXxYi30z7Ds0Cqv0bP9jDhVmFr0u1tSJoN7ZLRgiE3Sw2xTVp3GppDtVbJd8rp+ZSxNuonLTx9qljQJgE28C2KQEx0P23PwpVM/w63+u/5ViF1QQh2yF4wKAbNAOA9grLLoLArmU2ONI7VBLfzUmPoJsChXjyD1S2c1UkFzYDav1iuV2BMc6KGpnC3YqGW6eQzfLMUhV+xt48/83OIKxlpwn+EdokX7AdAToJr4Ui2wo++9j+6xGom3uyDMD+nnkqqbznTk59CutxS4+NZWp7BkLBemuLTaeiGGjiY1J4qFq6CDvoAOJca2w2A2tkh+Dz/GQKvrsvUqBA42CQDrVNWhQhwMAx+zIMTi2Ytxt3cPVFaU54R5h0wHg/r1HmkuLufGIt/yeJwpaeAdO4nOAlBr88J525ggWFPoYTkhaXozIT7LzqmLK/zc72JHb0DAITue+1v1P/K87RTakAv2f6kt4Qbb2InzaEc=
  bucket: ${S3_BUCKET_NAME}
  skip_cleanup: true
  acl: public_read
  region: ${S3_BUCKET_REGION}
  local_dir: $TRAVIS_BUILD_DIR/report/
after_deploy:
- cd ./
- chmod 744 parse_result.sh
- sh parse_result.sh || travis_terminate 1;