language: java
sudo: true
addons:
  apt:
    packages:
    - oracle-java8-installer
    - nodejs
install:
- wget -c https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-2.13.tgz
- tar -xf apache-jmeter-2.13.tgz
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4-sources.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4-javadoc.jar
- wget -P ./apache-jmeter-2.13/lib/ext https://github.com/maciejzaleski/JMeter-WebSocketSampler/releases/download/version-1.0.2/JMeterWebSocketSampler-1.0.2-SNAPSHOT.jar
- wget -c https://github.com/MCS-Lite/mcs-lite-app/releases/download/v1.0.6/7688.tar.gz
- tar -zxf 7688.tar.gz && cd 7688
- node server.js&
- cd .. && pwd
before_script:
- ls -al
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/ant-jmeter-1.1.1.jar ./
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/collapse.png ./
- cp $TRAVIS_BUILD_DIR/apache-jmeter-2.13/extras/expand.png ./
- ls -al
branches:
  only:
  - master
  - feature/auto-build
script:
- jdk_switcher use oraclejdk8
- ant -buildfile build.xml -Dtestpath=./ -Dtest=SmokeTest_lite -Djmeter.home="$TRAVIS_BUILD_DIR/apache-jmeter-2.13"
  -Dmcslite.host="localhost" -Dmcslite.port="80"
deploy:
  provider: s3
  access_key_id: AKIAIMAKZS4RGLFOI2EQ
  secret_access_key:
    secure: NBE/u4wplR25S8RSRyJu3Aw1OHCLFac8wVxfVmyBLD8vIqJ7ISrwMh3yJQ4PIOc68JirA22G0FNwgRzBhu1omrebXlGTiLMaQixSZ3slv9bcWFnagV5uLt0SF16+qt9gZP1f86MelCvk4uH7YS/Pel+KtcIQHNwnpywpbfuFpX0eD7Tm9DIHs1S/urTgNSQ0ZCViQaRhL0X5euVdXV/GFLUQmIw8Y0LAZKRbSI5YKbTfVJH4Fy2U2Fu/HZAap+WSUQ9dWx5QfYKOrEcbAB3ldiQ7lG1KrVgFeu04V65tgHefRLu3e+Wehwv/I906hQbtAi4Z0hmOX3Lm61Xy68q2zYf7PCSqJ3EyPmHWpdF/eIS16boEw617NqUTQG5vUyApZFzttx9YM2Y8WLhmJItrKKntiec6eJyVedG6YHE1EEPAbQyGLdFNHVw3mntlu3V9NAy2v2ulqyJvFLW2236C0bYMzcMZxG4SDGoE16OBSdAluKC89vwJWirPP+QCF9Gsdy53awl8/k9pLcxEL1BhMlG3SvYV6SXnz8VUFHksCxBAk7MkogtDM/hJ3Edz+cvXZlKZgp1eNSyfEKvIWy3W0Nf3KQQcn2LJqWMmEESRLtMveYPWGTM0+oABZVfguoq5pX4BInzhH2S2jPoQhxEL47eUiKxiDf7NTl+Cs25GFkU=
  bucket: ${S3_BUCKET_NAME}
  skip_cleanup: true
  acl: public_read
  region: ${S3_BUCKET_REGION}
  local_dir: $TRAVIS_BUILD_DIR/report/
  on:
    all_branches: true
after_deploy:
- cd ./
- chmod 744 parse_result.sh
- sh parse_result.sh || travis_terminate 1;